version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/node:16

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: ./tools/deploy.sh

workflows:
  # push workflow will be triggered when a new pull request is created
  build_and_test_branch:
    jobs:
      - build:
          context: cloud-hippie-global